In [1]:
import numpy as np

my_array = np.arange(8)

print(my_array)
print(type(my_array))


[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
my_array = np.arange(1, 8)

print(my_array)
print(type(my_array))


[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [3]:
my_array = np.arange(1, 8, 2)

print(my_array)
print(type(my_array))


[1 3 5 7]
<class 'numpy.ndarray'>


In [6]:
from_list = np.array([1, 2, 3], dtype=np.int8)

print(from_list)
print(type(from_list))
print(type(from_list[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [7]:
from_2d_list = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)

print(from_2d_list)
print(type(from_2d_list))
print(type(from_2d_list[0]))
print(type(from_2d_list[0][0]))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [8]:
from_2d_list = np.array((np.arange(0, 8, 2), np.arange(1, 8, 2)))

print(from_2d_list)
print(from_2d_list.shape)
print(type(from_2d_list))
print(type(from_2d_list[0]))
print(type(from_2d_list[0][0]))

[[0 2 4 6]
 [1 3 5 7]]
(2, 4)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [9]:
from_2d_list = np.array((np.arange(0, 8, 2), np.arange(1, 8, 2)))
from_2d_list = from_2d_list.reshape((4, 2))

print(from_2d_list)
print(from_2d_list.shape)
print(type(from_2d_list))
print(type(from_2d_list[0]))
print(type(from_2d_list[0][0]))

[[0 2]
 [4 6]
 [1 3]
 [5 7]]
(4, 2)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [12]:
from_2d_list = np.array((np.arange(0, 8, 2), np.arange(1, 8, 2)))
from_2d_list = from_2d_list.reshape(8)

print(from_2d_list)
print(from_2d_list.shape)
print(type(from_2d_list))
print(type(from_2d_list[0]))

[0 2 4 6 1 3 5 7]
(8,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [14]:
from_2d_list = np.array((np.arange(0, 8, 2), np.arange(1, 8, 2)))
from_2d_list = from_2d_list.reshape((2, 1, 4))

print(from_2d_list)
print(from_2d_list.shape)
print(type(from_2d_list))
print(type(from_2d_list[0]))
print(type(from_2d_list[0][0]))
print(type(from_2d_list[0][0][0]))

[[[0 2 4 6]]

 [[1 3 5 7]]]
(2, 1, 4)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [16]:
a = np.zeros((2, 2))

print(a)

[[0. 0.]
 [0. 0.]]


In [17]:
a = np.ones((2, 2))

print(a)

[[1. 1.]
 [1. 1.]]


In [27]:
a = np.empty((2, 2))

print(a)

[[1. 1.]
 [1. 1.]]


In [31]:
a = np.eye(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
a = np.eye(3, k=1)

print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [36]:
a = np.eye(3, k=1)
a[a == 0] = 2
a[a < 2] = 9

print(a)

[[2. 9. 2.]
 [2. 2. 9.]
 [2. 2. 2.]]


In [37]:
a = np.eye(3, k=1)
a[0] = 3
a[:2] = 3

print(a)

[[3. 3. 3.]
 [3. 3. 3.]
 [2. 2. 2.]]


In [38]:
a = np.eye(3, k=1)
a[:, 0] = 4

print(a)

[[4. 1. 0.]
 [4. 0. 1.]
 [4. 0. 0.]]


In [39]:
a = np.eye(3, k=1)
a[:, -1] = 4

print(a)

[[0. 1. 4.]
 [0. 0. 4.]
 [0. 0. 4.]]


In [40]:
a = np.eye(3, k=1)
a[1:, :2] = 4

print(a)

[[0. 1. 0.]
 [4. 4. 1.]
 [4. 4. 0.]]


In [43]:
a = np.eye(3, k=1)
a[1:, :2] = 4
s = np.sort(a)

print(a, "\n")
print(s)

[[0. 1. 0.]
 [4. 4. 1.]
 [4. 4. 0.]] 

[[0. 0. 1.]
 [1. 4. 4.]
 [0. 4. 4.]]


In [44]:
a = np.eye(3, k=1)
a[1:, :2] = 4
s = np.sort(a, 0)

print(a, "\n")
print(s)

[[0. 1. 0.]
 [4. 4. 1.]
 [4. 4. 0.]] 

[[0. 1. 0.]
 [4. 4. 0.]
 [4. 4. 1.]]


In [45]:
a = np.eye(3, k=1)
a[1:, :2] = 4
s = np.sort(a, 0, kind="mergesort")

print(a, "\n")
print(s)

[[0. 1. 0.]
 [4. 4. 1.]
 [4. 4. 0.]] 

[[0. 1. 0.]
 [4. 4. 0.]
 [4. 4. 1.]]


In [47]:
a = np.eye(3, k=1)
a[1:, :2] = 4
s = np.sort(a, 0, kind="mergesort")

copy1 = a.view() # shallow copy
copy2 = a.copy() # deep copy

copy1[:] = 4
copy2[:] = 4

print(a)
print(copy1)
print(copy2)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [49]:
a = np.linspace(2, 10, 5)
print(a)

[ 2.  4.  6.  8. 10.]


In [50]:
np.random.seed(0)
r = np.random.randint(10, size=6)
r

array([5, 0, 3, 3, 7, 9])